// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HorizontalScrollController from "./horizontal_scroll_controller"
application.register("horizontal-scroll", HorizontalScrollController)

import SweetAlertController from "./sweet_alert_controller"
application.register("sweet-alert", SweetAlertController)

import UpdateCompleteController from "./update_complete_controller"
application.register("update-complete", UpdateCompleteController)
